---
- hosts: localhost
  connection: local
  vars:
    fixed_font_family: "DejaVu Sans Mono"
  tasks:
    - name: Include sway.yml tasks
      include_tasks: sway.yml
      
    - name: Configure Vim
      copy:
        src: ../templates/vimrc.j2
        dest: ~/.vimrc
        mode: '0644'