---
# macOS-specific terminal configuration variables

# Shell paths
shell_paths:
  fish: "{{ homebrew_prefix }}/bin/fish"
  tmux: "{{ homebrew_prefix }}/bin/tmux"

# Font configuration for macOS
font_family: "SF Mono"
fixed_font_family: "SF Mono"

# Key bindings for macOS (cmd-based)
key_bindings:
  copy: "cmd+c"
  paste: "cmd+v"
  interrupt: "cmd+shift+c"
  suspend: "cmd+z"

# macOS-specific tmux settings
tmux_shell: "{{ homebrew_prefix }}/bin/fish"


