---
# macOS-specific terminal configuration variables

# Shell paths
shell_paths:
  fish: "{% if ansible_architecture == 'arm64' %}/opt/homebrew/bin/fish{% else %}/usr/local/bin/fish{% endif %}"
  homebrew_prefix: "{% if ansible_architecture == 'arm64' %}/opt/homebrew{% else %}/usr/local{% endif %}"

# Font configuration for macOS
font_family: "SF Mono"
fixed_font_family: "SF Mono"

# Key bindings for macOS (cmd-based)
key_bindings:
  copy: "cmd+c"
  paste: "cmd+v"
  interrupt: "cmd+shift+c"
  suspend: "cmd+z"

# macOS-specific tmux settings
tmux_shell: "{% if ansible_architecture == 'arm64' %}/opt/homebrew/bin/fish{% else %}/usr/local/bin/fish{% endif %}"

# Platform detection
is_mac: true

