- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: yes

- name: Install basics
  become: yes
  apt:
    name:
      - git
      - make
      - vim
      - wget
      - gpg
      - ncdu
      - htop
      - fish
      - flatpak
      - snap
      - python3
      - python3-venv
      - mc
      - udiskie
      - jack-midi-clock
      - build-essential
      - clang
      - nfs-common
      - wofi
      - grim
      - slurp
      - swaybg
    state: present

- name: Copy Git config
  become: no
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Create wip directory
  become: yes
  file:
    path: ~/wip
    state: directory
    mode: "0755"

- name: Create screenshots directory
  become: no
  file:
    path: ~/Pictures/screenshots
    state: directory
    mode: "0755"

- name: Create Wallpapers directory
  become: no
  file:
    path: ~/Pictures/Wallpapers
    state: directory
    mode: "0755"

- name: Ensure /etc/apt/keyrings directory exists
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Microsoft GPG key
  become: yes
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    mode: '0644'

- name: Add Microsoft GPG key
  become: yes
  apt_key:
    file: /etc/apt/keyrings/packages.microsoft.asc
    state: present

- name: Add Microsoft apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Update apt cache after adding Microsoft repository
  become: yes
  apt:
    update_cache: yes

- name: Install code
  become: yes
  apt:
    name:
      - code

- name: Ensure Snapd is installed (Snap's daemon)
  become: yes
  ansible.builtin.package:
    name: snapd
    state: present

- name: Ensure Discord is installed
  become: yes
  community.general.snap:
    name: discord
    classic: yes

- name: Ensure Steam is installed
  become: yes
  community.general.snap:
    name: steam
    classic: yes

- name: Ensure Spotify is installed
  become: yes
  community.general.snap:
    name: spotify
    classic: yes

- name: Install apps etc
  become: yes
  apt:
    name:
      - shotwell
    state: present

- name: Ensure core is installed
  become: yes
  community.general.snap:
    name: core

- name: Install Logseq
  become: yes
  ansible.builtin.shell: flatpak install flathub com.logseq.Logseq -y
