- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Install basics
  become: yes
  apt:
    name:
      - git
      - make
      - vim
      - wget
      - gpg
      - ncdu
      - htop
      - fish
      - flatpak
      - snap
      - python3.11-venv
    state: present

- name: Copy Git config
  become: no
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Create wip directory
  become: yes
  file: 
    path: ~/wip 
    state: directory 
    mode: "0755"

- name: Download Microsoft GPG key
  become: yes
  shell: wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /etc/apt/keyrings/packages.microsoft.gpg

- name: Add Microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Install code
  become: yes
  apt:
    name:
      - code

- name: Ensure Snapd is installed (Snap's daemon)
  become: yes
  ansible.builtin.package:
    name: snapd
    state: present

- name: Ensure Spotify is instaled
  become: yes
  community.general.snap:
    name: spotify
    classic: yes

- name: Ensure core is installed
  become: yes
  community.general.snap:
    name: core

- name: Install Logseq
  become: yes
  ansible.builtin.shell: flatpak install flathub com.logseq.Logseq -y
