- hosts: localhost
  connection: local
  handlers:
    - include_tasks: handlers/main.yml
  tasks:
    - name: Include basics.yml tasks
      include_tasks: basics.yml

    - name: Include applications.yml tasks
      include_tasks: applications.yml

    - name: Include sway.yml tasks
      include_tasks: sway.yml

    - name: Include development tools tasks
      include_tasks: tasks/development.yml

    - name: Include Android tools tasks
      include_tasks: tasks/android.yml

    - name: Include music.yml tasks
      include_tasks: music.yml
