---
- hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Require HAL for the Sunshine Host role
      ansible.builtin.assert:
        that:
          - ansible_facts['hostname'] == 'hal'
        fail_msg: "The sunshine-host role is only assigned to HAL."
  roles:
    - sunshine-host
