- name: Install sway
  become: yes
  apt:
    name: 
      - sway
      - kitty
    state: present

- name: Ensure the configuration directory exists
  ansible.builtin.file:
    path: ~/.config/sway 
    state: directory
    mode: '0755'

- name: Copy sway config 
  become: no
  template:
    src: swayconfig.j2
    dest: ~/.config/sway/config

- name: Ensure the kitty configuration directory exists
  ansible.builtin.file:
    path: ~/.config/kitty
    state: directory
    mode: '0755'

- name: Copy kitty config 
  become: no
  template:
    src: kittyconfig.j2
    dest: ~/.config/kitty/kitty.conf