- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Upgrade all packages
  become: yes
  apt:
    upgrade: yes

- name: Install basics
  become: yes
  apt:
    name:
      - git
      - make
      - vim
      - wget
      - gpg
      - ncdu
      - htop
      - fish
      - python3
      - python3-venv
      - mc
      - udiskie
      - jack-midi-clock
      - build-essential
      - clang
      - nfs-common
      - wofi
      - grim
      - slurp
    state: present

- name: Copy Git config
  become: no
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: Create wip directory
  become: yes
  file:
    path: ~/wip
    state: directory
    mode: "0755"

- name: Ensure /etc/apt/keyrings directory exists
  become: yes
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Microsoft GPG key
  become: yes
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/keyrings/packages.microsoft.asc
    mode: '0644'

- name: Add Microsoft GPG key
  become: yes
  apt_key:
    file: /etc/apt/keyrings/packages.microsoft.asc
    state: present

- name: Add Microsoft apt repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main
    filename: vscode
    state: present

- name: Update apt cache after adding Microsoft repository
  become: yes
  apt:
    update_cache: yes

- name: Install code
  become: yes
  apt:
    name:
      - code
