---
- name: Setup Node.js 20.x repository
  become: true
  ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
  args:
    creates: /etc/apt/sources.list.d/nodesource.list
  register: nodejs_repo_setup
  
- name: Install npm
  become: true
  package:
    name: nodejs
    state: present
  register: npm_install

- name: Install rustup
  become: true
  package:
    name: rustup
    state: present

- name: Initialize rustup with stable toolchain
  become: true
  ansible.builtin.shell: rustup default stable
  args:
    creates: "{{ ansible_env.HOME }}/.rustup"
  changed_when: false

- name: Install tig
  become: true
  package:
    name: tig
    state: present

- name: Install ack-grep
  become: true
  package:
    name: ack-grep
    state: present

- name: Install other tools (e.g., bat, fd-find, ripgrep)
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bat
    - fd-find
    - ripgrep