---
- name: Install npm
  become: true
  package:
    name: npm
    state: present

- name: Install rustup
  become: true
  package:
    name: rustup
    state: present

- name: Initialize rustup with stable toolchain
  become: true
  ansible.builtin.shell: rustup default stable
  args:
    creates: "{{ ansible_env.HOME }}/.rustup"
  changed_when: false

- name: Install tig
  become: true
  package:
    name: tig
    state: present

- name: Install ack-grep
  become: true
  package:
    name: ack-grep
    state: present

- name: Install other tools (e.g., bat, fd-find, ripgrep)
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bat
    - fd-find
    - ripgrep