---
- name: Create local bin directory
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: '0755'

- name: Install wallpaper rotation script
  copy:
    src: wallpaper-rotate.sh
    dest: "{{ ansible_env.HOME }}/.local/bin/wallpaper-rotate.sh"
    mode: '0755'

- name: Create wallpapers directory
  file:
    path: "{{ ansible_env.HOME }}/Pictures/wallpapers"
    state: directory
    mode: '0755'