---
- name: Install JACK and audio packages
  apt:
    name:
      - jackd2
      - jack-tools
      - qjackctl
      - libjack-jackd2-dev
      - pulseaudio-module-jack
      - a2jmidid
      - ffmpeg
      - alsa-utils
      - linux-image-raspi
      - python3-jack-client
      - python3-soundfile
      - python3-numpy
    state: present
    update_cache: yes
  become: yes
