---
- name: Check for npm availability
  command: npm --version
  register: npm_check
  changed_when: false
  failed_when: false

- name: Fail if npm is not available
  fail:
    msg: >-
      npm is not available on PATH. Node.js installation should provide npm,
      but it appears missing. Please review Node.js install tasks for this host.
  when: npm_check.rc != 0

- name: Install/Update Claude Code globally
  npm:
    name: "@anthropic-ai/claude-code"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: claude_install_result

- name: Install/Update Gemini CLI globally
  npm:
    name: "@google/gemini-cli"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: gemini_install_result

- name: Install/Update OpenAI Codex globally
  npm:
    name: "@openai/codex"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Install/Update OpenCode AI globally
  npm:
    name: "opencode-ai"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: opencode_install_result

- name: Display Claude Code installation status
  debug:
    msg: "Claude Code {{ 'updated' if claude_install_result.changed else 'already up to date' }}"

- name: Display Gemini CLI installation status
  debug:
    msg: "Gemini CLI {{ 'updated' if gemini_install_result.changed else 'already up to date' }}"

- name: Display OpenCode AI installation status
  debug:
    msg: "OpenCode AI {{ 'updated' if opencode_install_result.changed else 'already up to date' }}"
