---
- name: Install/Update Claude Code globally
  npm:
    name: "@anthropic-ai/claude-code"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: claude_install_result

- name: Install/Update Gemini CLI globally
  npm:
    name: "@google/gemini-cli"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: gemini_install_result

- name: Install/Update OpenCode AI globally
  npm:
    name: "opencode-ai"
    global: yes
    state: latest
  become: "{{ ansible_os_family != 'Darwin' }}"
  register: opencode_install_result

- name: Display Claude Code installation status
  debug:
    msg: "Claude Code {{ 'updated' if claude_install_result.changed else 'already up to date' }}"

- name: Display Gemini CLI installation status
  debug:
    msg: "Gemini CLI {{ 'updated' if gemini_install_result.changed else 'already up to date' }}"

- name: Display OpenCode AI installation status
  debug:
    msg: "OpenCode AI {{ 'updated' if opencode_install_result.changed else 'already up to date' }}"