---
- name: Load common terminal variables
  include_vars: ../../terminal/vars/common.yml

- name: Load OS-specific terminal variables (Darwin)
  include_vars: ../../terminal/vars/darwin.yml
  when: is_mac

- name: Load OS-specific terminal variables (Debian)
  include_vars: ../../terminal/vars/debian.yml
  when: is_linux and ansible_os_family == 'Debian'

- name: Check if kitty is installed
  command: which kitty
  register: kitty_check
  failed_when: false
  changed_when: false

- name: Configure kitty terminal
  when: kitty_check.rc == 0
  block:
    - name: Create kitty config directory
      file:
        path: "{{ ansible_env.HOME }}/.config/kitty"
        state: directory
        mode: '0755'

    - name: Deploy kitty configuration
      template:
        src: kittyconfig.j2
        dest: "{{ ansible_env.HOME }}/.config/kitty/kitty.conf"
        mode: '0644'
      tags: kitty