---
- name: Set platform facts
  set_fact:
    is_mac: "{{ ansible_facts['os_family'] == 'Darwin' }}"
    is_linux: "{{ ansible_facts['os_family'] in ['Debian', 'RedHat'] }}"
    is_arm: "{{ ansible_architecture == 'arm64' or ansible_architecture == 'aarch64' }}"
    homebrew_prefix: "{{ '/opt/homebrew' if ansible_architecture == 'arm64' else '/usr/local' }}"
    platform_name: "{{ 'ubuntu' if ansible_os_family == 'Debian' else ansible_os_family | lower }}"

- name: Display detected platform information
  debug:
    msg:
      - "Platform: {{ ansible_os_family }} ({{ ansible_system }})"
      - "Architecture: {{ ansible_architecture }}"
      - "Is Mac: {{ is_mac }}"
      - "Is Linux: {{ is_linux }}"
      - "Is ARM: {{ is_arm }}"
      - "Homebrew prefix: {{ homebrew_prefix }}"
      - "Platform name: {{ platform_name }}"