---
- name: Drop /etc/profile.d/secret_env.sh for bash/zsh fallback
  copy:
    dest: /etc/profile.d/secret_env.sh
    content: |
      [ -f "$HOME/.secret_env" ] && . "$HOME/.secret_env"
    mode: "0644"
  become: yes
  when: is_linux