---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install dependencies
  apt:
    name:
      - build-essential
      - cmake
      - git
      - wget
      - python3
      - python3-venv
      - libopenblas-dev
      - libcurl4-openssl-dev
    state: present
  become: yes

- name: Clone llama.cpp repository
  git:
    repo: https://github.com/ggerganov/llama.cpp.git
    dest: /opt/llama.cpp
    version: HEAD
  become: yes

- name: Configure llama.cpp build with CMake
  command: cmake -B build -DLLAMA_OPENBLAS=ON -DGGML_CPU_AARCH64=OFF
  args:
    chdir: /opt/llama.cpp
  become: yes

- name: Build llama.cpp with CMake
  command: cmake --build build -j{{ ansible_processor_vcpus }}
  args:
    chdir: /opt/llama.cpp
  become: yes

- name: Create symlinks in /usr/local/bin for easy access
  file:
    src: /opt/llama.cpp/build/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  become: yes
  loop:
    - llama-cli
    - llama-server