---
- name: Install sway
  become: yes
  apt:
    name: 
      - sway
      - swayidle
      - swaylock
      - fonts-oxygen
      - waybar
      - upower
      - kitty
      - light
      - swaybg
      - wev
      - pavucontrol
      - network-manager
      - brightnessctl
      - wofi
      - grim
      - slurp
    state: present

- name: Ensure user in video group (for backlight control)
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: video
    append: yes

- name: Ensure the sway configuration directory exists
  become: no
  ansible.builtin.file:
    path: ~/.config/sway 
    state: directory
    mode: '0755'

- name: Ensure user environment.d directory exists
  become: no
  ansible.builtin.file:
    path: ~/.config/environment.d
    state: directory
    mode: '0755'

- name: Set wlroots DRM environment flags
  become: no
  ansible.builtin.template:
    src: wlroots.conf.j2
    dest: ~/.config/environment.d/wlroots.conf
    mode: '0644'

- name: Copy sway config
  become: no
  template:
    src: swayconfig.j2
    dest: ~/.config/sway/config
  notify: reload sway

- name: Ensure the waybar configuration directory exists
  become: no
  ansible.builtin.file:
    path: ~/.config/waybar
    state: directory
    mode: '0755'

- name: Include wallpaper tasks
  include_tasks: wallpaper.yml


- name: Copy config 
  become: no
  template:
    src: waybar.j2
    dest: ~/.config/waybar/config.jsonc
  notify: reload sway

- name: Copy waybar style
  become: no
  template:
    src: waybar.css.j2
    dest: ~/.config/waybar/style.css
  notify: reload sway


- name: Install udev rules for screen/keyboard backlight
  become: yes
  copy:
    src: 90-backlight.rules
    dest: /etc/udev/rules.d/90-backlight.rules
    owner: root
    group: root
    mode: '0644'
  notify: reload udev


- name: Create screenshots directory
  become: no
  file:
    path: ~/Pictures/screenshots
    state: directory
    mode: "0755"

- name: Create wallpapers directory
  become: no
  file:
    path: ~/Pictures/wallpapers
    state: directory
    mode: "0755"

- name: Ensure wofi configuration directory exists
  ansible.builtin.file:
    path: ~/.config/wofi
    state: directory
    mode: '0755'

- name: Copy wofi config file
  template:
    src: wofi-config.j2
    dest: ~/.config/wofi/config

- name: Copy wofi style file
  template:
    src: wofi-style.css.j2
    dest: ~/.config/wofi/style.css

- name: Include kanshi tasks
  include_tasks: kanshi.yml

- name: Ensure applications directory exists
  become: no
  ansible.builtin.file:
    path: ~/.local/share/applications
    state: directory
    mode: '0755'

- name: Add RimWorld launcher (.desktop)
  become: no
  ansible.builtin.template:
    src: rimworld.desktop.j2
    dest: ~/.local/share/applications/rimworld.desktop
    mode: '0644'
