---
- name: Include platform detection
  include_tasks: ../core-tools/tasks/platform_detection.yml

- name: Load common variables
  include_vars: common.yml

- name: Load OS-specific variables (Darwin)
  include_vars: darwin.yml
  when: is_mac

- name: Check if Homebrew is installed
  stat:
    path: "{{ homebrew_prefix }}/bin/brew"
  register: homebrew_check
  when: is_mac

- name: Set homebrew shellenv command
  set_fact:
    homebrew_shellenv: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"'
  when: is_mac and homebrew_check.stat.exists

- name: Load OS-specific variables (Debian/Ubuntu)
  include_vars: debian.yml
  when: is_linux and ansible_os_family == 'Debian'

- name: Configure terminal components
  include_tasks: "{{ item }}.yml"
  loop: "{{ terminal_components }}"
  tags: 
    - terminal