---
- name: Copy blank template (first run only, never overwrite)
  copy:
    src: secret_env.template
    dest: "{{ ansible_env.HOME }}/.secret_env.template"
    mode: "0644"
    force: no

- name: Ensure real secret file exists (user fills this in)
  file:
    path: "{{ ansible_env.HOME }}/.secret_env"
    state: touch
    mode: "0600"

- name: Add .secret_env to gitignore
  lineinfile:
    path: "{{ playbook_dir }}/.gitignore"
    line: ".secret_env"
    state: present