---
- name: Install OpenSSH server
  package:
    name: openssh-server
    state: present
  when: ansible_os_family == "Debian"

- name: Ensure SSH service is enabled and running
  systemd:
    name: ssh
    enabled: yes
    state: started
  when: ansible_os_family == "Debian"

- name: Copy SSH banner
  copy:
    src: ssh_banner
    dest: /etc/ssh/ssh_banner
    mode: '0644'
    owner: root
    group: root

- name: Configure SSH daemon
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^#?PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^#?PubkeyAuthentication', line: 'PubkeyAuthentication yes' }
    - { regexp: '^#?AuthorizedKeysFile', line: 'AuthorizedKeysFile .ssh/authorized_keys' }
    - { regexp: '^#?PermitRootLogin', line: 'PermitRootLogin no' }
    - { regexp: '^#?Banner', line: 'Banner /etc/ssh/ssh_banner' }
    - { regexp: '^#?PrintMotd', line: 'PrintMotd no' }
  notify: restart ssh

- name: Disable PAM MOTD in SSH
  lineinfile:
    path: /etc/pam.d/sshd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^session\s+optional\s+pam_motd\.so', line: '# session    optional     pam_motd.so' }
    - { regexp: '^session\s+optional\s+pam_motd\.so\s+motd=/run/motd\.dynamic', line: '# session    optional     pam_motd.so motd=/run/motd.dynamic' }

- name: Remove executable permissions from update-motd scripts
  file:
    path: "{{ item }}"
    mode: '0644'
  with_items:
    - /etc/update-motd.d/00-header
    - /etc/update-motd.d/10-help-text
    - /etc/update-motd.d/50-motd-news
    - /etc/update-motd.d/80-esm
    - /etc/update-motd.d/90-updates-available
    - /etc/update-motd.d/95-hwe-eol
  ignore_errors: yes

- name: Ensure .ssh directory exists for system user
  file:
    path: "/home/system/.ssh"
    state: directory
    mode: '0700'
    owner: system
    group: system

- name: Add authorized SSH public keys
  blockinfile:
    path: "/home/system/.ssh/authorized_keys"
    block: "{{ lookup('file', item) }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item | basename }}"
    create: yes
    mode: '0600'
    owner: system
    group: system
    backup: yes
  with_fileglob:
    - "files/ssh_keys/*.pub"